/**
 * Core Dictionary - Generated by scripts/generate_dictionary.py
 * DO NOT EDIT MANUALLY - Run the script to regenerate
 * 
 * This is Tier 1 dictionary - always loaded (~140 words)
 * Tier 2 (extended) is lazy-loaded from JSON
 */

export interface DictionaryEntry {
  khmer: string;
  english: string;
  pos?: 'noun' | 'verb' | 'adj' | 'adv' | 'pron' | 'prep' | 'conj' | 'part' | 'num';
  romanized?: string;
  phonetic?: string;
  frequency?: number;
}

export const coreDictionary: DictionaryEntry[] = [
  { khmer: 'សួស្តី', english: 'hello', pos: 'noun', romanized: 'suă-stei', phonetic: 'SUA-STAY', frequency: 100 },
  { khmer: 'អរគុណ', english: 'thank you', pos: 'noun', romanized: '\'rkŭ-nâ', phonetic: 'RKU-NA', frequency: 100 },
  { khmer: 'សូម', english: 'please', pos: 'part', romanized: 'so-mô', phonetic: 'SOH-MO', frequency: 95 },
  { khmer: 'សូមទោស', english: 'sorry/excuse me', pos: 'noun', romanized: 'so-mto-sâ', phonetic: 'SOH-MTOH-SA', frequency: 90 },
  { khmer: 'បាទ', english: 'yes (male)', pos: 'part', romanized: 'bā-tô', phonetic: 'BAH-TO', frequency: 100 },
  { khmer: 'ចាស', english: 'yes (female)', pos: 'part', romanized: 'chā-sâ', phonetic: 'CHAH-SA', frequency: 100 },
  { khmer: 'ទេ', english: 'no/not', pos: 'part', romanized: 'té', phonetic: 'TAY', frequency: 100 },
  { khmer: 'មិន', english: 'not', pos: 'adv', romanized: 'mĭ-nô', phonetic: 'MI-NO', frequency: 95 },
  { khmer: 'ខ្ញុំ', english: 'I/me', pos: 'pron', romanized: 'khñŏm', phonetic: 'KHNYOM', frequency: 100 },
  { khmer: 'អ្នក', english: 'you', pos: 'pron', romanized: '\'nâ-kâ', phonetic: 'NA-KA', frequency: 100 },
  { khmer: 'គាត់', english: 'he/she/they', pos: 'pron', romanized: 'kā-tâ', phonetic: 'KAH-TA', frequency: 95 },
  { khmer: 'យើង', english: 'we', pos: 'pron', romanized: 'yeu-ngô', phonetic: 'YEU-NGO', frequency: 90 },
  { khmer: 'គេ', english: 'they/people', pos: 'pron', romanized: 'ké', phonetic: 'KAY', frequency: 85 },
  { khmer: 'នេះ', english: 'this', pos: 'pron', romanized: 'néh', phonetic: 'NAYH', frequency: 95 },
  { khmer: 'នោះ', english: 'that', pos: 'pron', romanized: 'noh', phonetic: 'NOHH', frequency: 95 },
  { khmer: 'អី', english: 'what', pos: 'pron', romanized: '\'ei', phonetic: 'AY', frequency: 90 },
  { khmer: 'អ្វី', english: 'what (formal)', pos: 'pron', romanized: '\'vei', phonetic: 'VAY', frequency: 90 },
  { khmer: 'ណា', english: 'where/which', pos: 'pron', romanized: 'nā', phonetic: 'NAH', frequency: 90 },
  { khmer: 'នរណា', english: 'who', pos: 'pron', romanized: 'nrnā', phonetic: 'NRNAH', frequency: 85 },
  { khmer: 'ទៅ', english: 'go', pos: 'verb', romanized: 'tŏu', phonetic: 'TOU', frequency: 100 },
  { khmer: 'មក', english: 'come', pos: 'verb', romanized: 'mkâ', phonetic: 'MKA', frequency: 100 },
  { khmer: 'ញ៉ាំ', english: 'eat', pos: 'verb', romanized: 'ñām', phonetic: 'NYAHM', frequency: 95 },
  { khmer: 'ផឹក', english: 'drink', pos: 'verb', romanized: 'phœ̆-kâ', phonetic: 'PHEU-KA', frequency: 90 },
  { khmer: 'ដឹង', english: 'know', pos: 'verb', romanized: 'dœ̆-ngô', phonetic: 'DEU-NGO', frequency: 95 },
  { khmer: 'ចង់', english: 'want', pos: 'verb', romanized: 'chngô', phonetic: 'CHNGO', frequency: 95 },
  { khmer: 'មាន', english: 'have/there is', pos: 'verb', romanized: 'mā-nô', phonetic: 'MAH-NO', frequency: 100 },
  { khmer: 'ធ្វើ', english: 'do/make', pos: 'verb', romanized: 'thveu', phonetic: 'THVEU', frequency: 95 },
  { khmer: 'និយាយ', english: 'speak/say', pos: 'verb', romanized: 'nĭ-yā-yô', phonetic: 'NI-YAH-YO', frequency: 90 },
  { khmer: 'មើល', english: 'look/watch', pos: 'verb', romanized: 'meu-lô', phonetic: 'MEU-LO', frequency: 90 },
  { khmer: 'ស្តាប់', english: 'listen', pos: 'verb', romanized: 'stā-bâ', phonetic: 'STAH-BA', frequency: 85 },
  { khmer: 'អាន', english: 'read', pos: 'verb', romanized: '\'ā-nô', phonetic: 'AH-NO', frequency: 85 },
  { khmer: 'សរសេរ', english: 'write', pos: 'verb', romanized: 'srsé-rô', phonetic: 'SRSAY-RO', frequency: 85 },
  { khmer: 'ស្រឡាញ់', english: 'love', pos: 'verb', romanized: 'srâ-lā-ñô', phonetic: 'SRA-LAH-NYO', frequency: 90 },
  { khmer: 'ចូលចិត្ត', english: 'like', pos: 'verb', romanized: 'cho-lchĕ-ttâ', phonetic: 'CHOH-LCHE-TTA', frequency: 90 },
  { khmer: 'ជឿ', english: 'believe', pos: 'verb', romanized: 'chœă', phonetic: 'CHEUA', frequency: 80 },
  { khmer: 'គិត', english: 'think', pos: 'verb', romanized: 'kĭ-tâ', phonetic: 'KI-TA', frequency: 85 },
  { khmer: 'ដេក', english: 'sleep', pos: 'verb', romanized: 'dé-kâ', phonetic: 'DAY-KA', frequency: 85 },
  { khmer: 'ក្រោក', english: 'wake up/get up', pos: 'verb', romanized: 'krau-kâ', phonetic: 'KRAO-KA', frequency: 80 },
  { khmer: 'រត់', english: 'run', pos: 'verb', romanized: 'rtâ', phonetic: 'RTA', frequency: 75 },
  { khmer: 'ដើរ', english: 'walk', pos: 'verb', romanized: 'daeu-rô', phonetic: 'DEU-RO', frequency: 80 },
  { khmer: 'ជិះ', english: 'ride', pos: 'verb', romanized: 'chĭh', phonetic: 'CHIH', frequency: 75 },
  { khmer: 'ឈប់', english: 'stop', pos: 'verb', romanized: 'chhbâ', phonetic: 'CHHBA', frequency: 80 },
  { khmer: 'ចាំ', english: 'wait/remember', pos: 'verb', romanized: 'chām', phonetic: 'CHAHM', frequency: 85 },
  { khmer: 'ភ្លេច', english: 'forget', pos: 'verb', romanized: 'phlé-châ', phonetic: 'PHLAY-CHA', frequency: 75 },
  { khmer: 'ទិញ', english: 'buy', pos: 'verb', romanized: 'tĭ-ñô', phonetic: 'TI-NYO', frequency: 85 },
  { khmer: 'លក់', english: 'sell', pos: 'verb', romanized: 'lkâ', phonetic: 'LKA', frequency: 80 },
  { khmer: 'ផ្តល់', english: 'give', pos: 'verb', romanized: 'phtâ-lô', phonetic: 'PHTA-LO', frequency: 80 },
  { khmer: 'យក', english: 'take', pos: 'verb', romanized: 'ykâ', phonetic: 'YKA', frequency: 85 },
  { khmer: 'ដាក់', english: 'put', pos: 'verb', romanized: 'dā-kâ', phonetic: 'DAH-KA', frequency: 80 },
  { khmer: 'មួយ', english: 'one', pos: 'num', romanized: 'muŏ-yô', phonetic: 'MUO-YO', frequency: 100 },
  { khmer: 'ពីរ', english: 'two', pos: 'num', romanized: 'pī-rô', phonetic: 'PEE-RO', frequency: 100 },
  { khmer: 'បី', english: 'three', pos: 'num', romanized: 'bei', phonetic: 'BAY', frequency: 100 },
  { khmer: 'បួន', english: 'four', pos: 'num', romanized: 'buă-nô', phonetic: 'BUA-NO', frequency: 95 },
  { khmer: 'ប្រាំ', english: 'five', pos: 'num', romanized: 'brām', phonetic: 'BRAHM', frequency: 95 },
  { khmer: 'ប្រាំមួយ', english: 'six', pos: 'num', romanized: 'brām-muŏ-yô', phonetic: 'BRAHM-MUO-YO', frequency: 90 },
  { khmer: 'ប្រាំពីរ', english: 'seven', pos: 'num', romanized: 'brām-pī-rô', phonetic: 'BRAHM-PEE-RO', frequency: 90 },
  { khmer: 'ប្រាំបី', english: 'eight', pos: 'num', romanized: 'brām-bei', phonetic: 'BRAHM-BAY', frequency: 90 },
  { khmer: 'ប្រាំបួន', english: 'nine', pos: 'num', romanized: 'brām-buă-nô', phonetic: 'BRAHM-BUA-NO', frequency: 90 },
  { khmer: 'ដប់', english: 'ten', pos: 'num', romanized: 'dbâ', phonetic: 'DBA', frequency: 95 },
  { khmer: 'រយ', english: 'hundred', pos: 'num', romanized: 'ryô', phonetic: 'RYO', frequency: 85 },
  { khmer: 'ពាន់', english: 'thousand', pos: 'num', romanized: 'pā-nô', phonetic: 'PAH-NO', frequency: 80 },
  { khmer: 'ថ្ងៃ', english: 'day', pos: 'noun', romanized: 'thngai', phonetic: 'THNGAI', frequency: 95 },
  { khmer: 'យប់', english: 'night', pos: 'noun', romanized: 'ybâ', phonetic: 'YBA', frequency: 90 },
  { khmer: 'ព្រឹក', english: 'morning', pos: 'noun', romanized: 'prœ̆-kâ', phonetic: 'PREU-KA', frequency: 90 },
  { khmer: 'ល្ងាច', english: 'evening', pos: 'noun', romanized: 'lngā-châ', phonetic: 'LNGAH-CHA', frequency: 85 },
  { khmer: 'ម៉ោង', english: 'hour/time', pos: 'noun', romanized: 'mau-ngô', phonetic: 'MAO-NGO', frequency: 90 },
  { khmer: 'នាទី', english: 'minute', pos: 'noun', romanized: 'nā-tī', phonetic: 'NAH-TEE', frequency: 80 },
  { khmer: 'ឥឡូវ', english: 'now', pos: 'adv', romanized: 'lo-vô', phonetic: 'LOH-VO', frequency: 90 },
  { khmer: 'ម្សិលមិញ', english: 'yesterday', pos: 'noun', romanized: 'msĭ-lmĭ-ñô', phonetic: 'MSI-LMI-NYO', frequency: 80 },
  { khmer: 'ថ្ងៃនេះ', english: 'today', pos: 'noun', romanized: 'thngai-néh', phonetic: 'THNGAI-NAYH', frequency: 90 },
  { khmer: 'ថ្ងៃស្អែក', english: 'tomorrow', pos: 'noun', romanized: 'thngai-s\'ê-kâ', phonetic: 'THNGAI-SEH-KA', frequency: 85 },
  { khmer: 'ផ្ទះ', english: 'house/home', pos: 'noun', romanized: 'phtâh', phonetic: 'PHTAH', frequency: 95 },
  { khmer: 'សាលា', english: 'school', pos: 'noun', romanized: 'sā-lā', phonetic: 'SAH-LAH', frequency: 85 },
  { khmer: 'ផ្សារ', english: 'market', pos: 'noun', romanized: 'phsā-rô', phonetic: 'PHSAH-RO', frequency: 90 },
  { khmer: 'មន្ទីរពេទ្យ', english: 'hospital', pos: 'noun', romanized: 'mntī-rpé-tyô', phonetic: 'MNTEE-RPAY-TYO', frequency: 75 },
  { khmer: 'វត្ត', english: 'temple/pagoda', pos: 'noun', romanized: 'vttâ', phonetic: 'VTTA', frequency: 80 },
  { khmer: 'ភូមិ', english: 'village', pos: 'noun', romanized: 'phū-mĭ', phonetic: 'PHOO-MI', frequency: 80 },
  { khmer: 'ទីក្រុង', english: 'city', pos: 'noun', romanized: 'tī-krŏ-ngô', phonetic: 'TEE-KRO-NGO', frequency: 80 },
  { khmer: 'ប្រទេស', english: 'country', pos: 'noun', romanized: 'brâ-té-sâ', phonetic: 'BRA-TAY-SA', frequency: 80 },
  { khmer: 'កម្ពុជា', english: 'Cambodia', pos: 'noun', romanized: 'kmpŭ-chā', phonetic: 'KMPU-CHAH', frequency: 95 },
  { khmer: 'ឆ្វេង', english: 'left', pos: 'noun', romanized: 'chhvé-ngô', phonetic: 'CHHVAY-NGO', frequency: 80 },
  { khmer: 'ស្តាំ', english: 'right', pos: 'noun', romanized: 'stām', phonetic: 'STAHM', frequency: 80 },
  { khmer: 'មុខ', english: 'front/face', pos: 'noun', romanized: 'mŭ-khâ', phonetic: 'MU-KHA', frequency: 85 },
  { khmer: 'ក្រោយ', english: 'behind/after', pos: 'prep', romanized: 'krau-yô', phonetic: 'KRAO-YO', frequency: 85 },
  { khmer: 'លើ', english: 'on/above', pos: 'prep', romanized: 'leu', phonetic: 'LEU', frequency: 85 },
  { khmer: 'ក្រោម', english: 'under/below', pos: 'prep', romanized: 'krau-mô', phonetic: 'KRAO-MO', frequency: 80 },
  { khmer: 'ក្នុង', english: 'in/inside', pos: 'prep', romanized: 'knŏ-ngô', phonetic: 'KNO-NGO', frequency: 90 },
  { khmer: 'ក្រៅ', english: 'outside', pos: 'prep', romanized: 'krau', phonetic: 'KRAO', frequency: 80 },
  { khmer: 'បាយ', english: 'rice (cooked)', pos: 'noun', romanized: 'bā-yô', phonetic: 'BAH-YO', frequency: 95 },
  { khmer: 'ទឹក', english: 'water', pos: 'noun', romanized: 'tœ̆-kâ', phonetic: 'TEU-KA', frequency: 95 },
  { khmer: 'សាច់', english: 'meat', pos: 'noun', romanized: 'sā-châ', phonetic: 'SAH-CHA', frequency: 85 },
  { khmer: 'ត្រី', english: 'fish', pos: 'noun', romanized: 'trei', phonetic: 'TRAY', frequency: 85 },
  { khmer: 'បន្លែ', english: 'vegetables', pos: 'noun', romanized: 'bnlê', phonetic: 'BNLEH', frequency: 80 },
  { khmer: 'ផ្លែឈើ', english: 'fruit', pos: 'noun', romanized: 'phlê-chheu', phonetic: 'PHLEH-CHHEU', frequency: 80 },
  { khmer: 'កាហ្វេ', english: 'coffee', pos: 'noun', romanized: 'kā-hvé', phonetic: 'KAH-HVAY', frequency: 80 },
  { khmer: 'តែ', english: 'tea', pos: 'noun', romanized: 'tê', phonetic: 'TEH', frequency: 80 },
  { khmer: 'ស្រា', english: 'alcohol/wine', pos: 'noun', romanized: 'srā', phonetic: 'SRAH', frequency: 70 },
  { khmer: 'មនុស្ស', english: 'person/people', pos: 'noun', romanized: 'mnŭ-ssâ', phonetic: 'MNU-SSA', frequency: 90 },
  { khmer: 'ម៉ែ', english: 'mother', pos: 'noun', romanized: 'mê', phonetic: 'MEH', frequency: 95 },
  { khmer: 'ប៉ា', english: 'father', pos: 'noun', romanized: 'bā', phonetic: 'BAH', frequency: 95 },
  { khmer: 'បង', english: 'older sibling', pos: 'noun', romanized: 'bngô', phonetic: 'BNGO', frequency: 95 },
  { khmer: 'អូន', english: 'younger sibling', pos: 'noun', romanized: '\'o-nô', phonetic: 'OH-NO', frequency: 95 },
  { khmer: 'កូន', english: 'child', pos: 'noun', romanized: 'ko-nô', phonetic: 'KOH-NO', frequency: 90 },
  { khmer: 'ប្រពន្ធ', english: 'wife', pos: 'noun', romanized: 'brâ-pnthô', phonetic: 'BRA-PNTHO', frequency: 80 },
  { khmer: 'ប្តី', english: 'husband', pos: 'noun', romanized: 'btei', phonetic: 'BTAY', frequency: 80 },
  { khmer: 'មិត្ត', english: 'friend', pos: 'noun', romanized: 'mĭ-ttâ', phonetic: 'MI-TTA', frequency: 85 },
  { khmer: 'ល្អ', english: 'good', pos: 'adj', romanized: 'l\'ô', phonetic: 'LO', frequency: 95 },
  { khmer: 'អាក្រក់', english: 'bad', pos: 'adj', romanized: '\'ā-krâ-kâ', phonetic: 'AH-KRA-KA', frequency: 85 },
  { khmer: 'ធំ', english: 'big', pos: 'adj', romanized: 'thôm', phonetic: 'THOM', frequency: 90 },
  { khmer: 'តូច', english: 'small', pos: 'adj', romanized: 'to-châ', phonetic: 'TOH-CHA', frequency: 90 },
  { khmer: 'ច្រើន', english: 'many/much', pos: 'adj', romanized: 'chraeu-nô', phonetic: 'CHREU-NO', frequency: 90 },
  { khmer: 'តិច', english: 'few/little', pos: 'adj', romanized: 'tĕ-châ', phonetic: 'TE-CHA', frequency: 85 },
  { khmer: 'ថ្មី', english: 'new', pos: 'adj', romanized: 'thmei', phonetic: 'THMAY', frequency: 85 },
  { khmer: 'ចាស់', english: 'old', pos: 'adj', romanized: 'chā-sâ', phonetic: 'CHAH-SA', frequency: 85 },
  { khmer: 'ក្តៅ', english: 'hot', pos: 'adj', romanized: 'ktau', phonetic: 'KTAO', frequency: 80 },
  { khmer: 'ត្រជាក់', english: 'cold', pos: 'adj', romanized: 'trâ-chā-kâ', phonetic: 'TRA-CHAH-KA', frequency: 80 },
  { khmer: 'ឆ្ងាញ់', english: 'delicious', pos: 'adj', romanized: 'chhngā-ñô', phonetic: 'CHHNGAH-NYO', frequency: 85 },
  { khmer: 'ស្អាត', english: 'beautiful/clean', pos: 'adj', romanized: 's\'ā-tâ', phonetic: 'SAH-TA', frequency: 85 },
  { khmer: 'លឿន', english: 'fast', pos: 'adj', romanized: 'lœă-nô', phonetic: 'LEUA-NO', frequency: 80 },
  { khmer: 'យឺត', english: 'slow', pos: 'adj', romanized: 'yœ-tâ', phonetic: 'YEU-TA', frequency: 75 },
  { khmer: 'ងាយ', english: 'easy', pos: 'adj', romanized: 'ngā-yô', phonetic: 'NGAH-YO', frequency: 80 },
  { khmer: 'ពិបាក', english: 'difficult', pos: 'adj', romanized: 'pĭ-bā-kâ', phonetic: 'PI-BAH-KA', frequency: 80 },
  { khmer: 'ថ្លៃ', english: 'expensive', pos: 'adj', romanized: 'thlai', phonetic: 'THLAI', frequency: 85 },
  { khmer: 'ថោក', english: 'cheap', pos: 'adj', romanized: 'thau-kâ', phonetic: 'THAO-KA', frequency: 80 },
  { khmer: 'ហេតុអ្វី', english: 'why', pos: 'adv', romanized: 'hé-tŏ-\'vei', phonetic: 'HAY-TO-VAY', frequency: 85 },
  { khmer: 'យ៉ាងម៉េច', english: 'how', pos: 'adv', romanized: 'yā-ngmé-châ', phonetic: 'YAH-NGMAY-CHA', frequency: 85 },
  { khmer: 'ប៉ុន្មាន', english: 'how many/much', pos: 'adv', romanized: 'bŏ-nmā-nô', phonetic: 'BO-NMAH-NO', frequency: 90 },
  { khmer: 'ពេលណា', english: 'when', pos: 'adv', romanized: 'pé-lnā', phonetic: 'PAY-LNAH', frequency: 85 },
  { khmer: 'សុខសប្បាយ', english: 'fine/well', pos: 'adj', romanized: 'sŏ-khsbbā-yô', phonetic: 'SO-KHSBBAH-YO', frequency: 90 },
  { khmer: 'អត់ទេ', english: 'no/nothing', pos: 'part', romanized: '\'tâ-té', phonetic: 'TA-TAY', frequency: 90 },
  { khmer: 'មែន', english: 'right/true', pos: 'adj', romanized: 'mê-nô', phonetic: 'MEH-NO', frequency: 90 },
  { khmer: 'បាន', english: 'can/got/already', pos: 'verb', romanized: 'bā-nô', phonetic: 'BAH-NO', frequency: 95 },
  { khmer: 'កំពុង', english: 'currently/-ing', pos: 'adv', romanized: 'kâm-pŭ-ngô', phonetic: 'KAM-PU-NGO', frequency: 85 },
  { khmer: 'រួច', english: 'already/finished', pos: 'adv', romanized: 'ruŏ-châ', phonetic: 'RUO-CHA', frequency: 85 },
  { khmer: 'នៅ', english: 'at/still', pos: 'prep', romanized: 'nŏu', phonetic: 'NOU', frequency: 95 },
  { khmer: 'និង', english: 'and', pos: 'conj', romanized: 'nĭ-ngô', phonetic: 'NI-NGO', frequency: 95 },
  { khmer: 'ឬ', english: 'or', pos: 'conj', frequency: 85 },
  { khmer: 'ប៉ុន្តែ', english: 'but', pos: 'conj', romanized: 'bŏ-ntê', phonetic: 'BO-NTEH', frequency: 85 },
  { khmer: 'ព្រោះ', english: 'because', pos: 'conj', romanized: 'proh', phonetic: 'PROHH', frequency: 80 },
  { khmer: 'ដូច្នេះ', english: 'so/therefore', pos: 'conj', romanized: 'do-chnéh', phonetic: 'DOH-CHNAYH', frequency: 75 },
];

// Build lookup maps for efficient access
const khmerToEntryMap = new Map<string, DictionaryEntry>();
const phoneticToEntryMap = new Map<string, DictionaryEntry[]>();

for (const entry of coreDictionary) {
  khmerToEntryMap.set(entry.khmer, entry);
  
  if (entry.phonetic) {
    const normalized = entry.phonetic.toLowerCase().replace(/-/g, '');
    if (!phoneticToEntryMap.has(normalized)) {
      phoneticToEntryMap.set(normalized, []);
    }
    phoneticToEntryMap.get(normalized)!.push(entry);
  }
}

/**
 * Look up a Khmer word in the dictionary
 */
export function lookupKhmer(word: string): DictionaryEntry | null {
  return khmerToEntryMap.get(word) || null;
}

/**
 * Fuzzy search by phonetic approximation
 */
export function searchByPhonetic(query: string): DictionaryEntry[] {
  const normalized = query.toLowerCase().replace(/[-\s]/g, '');
  const results: Array<{ entry: DictionaryEntry; score: number }> = [];
  
  for (const entry of coreDictionary) {
    if (!entry.phonetic) continue;
    
    const entryPhonetic = entry.phonetic.toLowerCase().replace(/-/g, '');
    const score = calculateSimilarity(normalized, entryPhonetic);
    
    if (score > 0.4) {
      results.push({ entry, score });
    }
  }
  
  return results
    .sort((a, b) => b.score - a.score)
    .slice(0, 10)
    .map(r => r.entry);
}

/**
 * Search by English meaning
 */
export function searchByEnglish(query: string): DictionaryEntry[] {
  const normalized = query.toLowerCase();
  const results: Array<{ entry: DictionaryEntry; score: number }> = [];
  
  for (const entry of coreDictionary) {
    const english = entry.english.toLowerCase();
    
    if (english === normalized) {
      results.push({ entry, score: 1 });
      continue;
    }
    
    if (english.includes(normalized) || normalized.includes(english)) {
      const score = Math.min(normalized.length, english.length) / Math.max(normalized.length, english.length);
      results.push({ entry, score: score * 0.8 });
    }
  }
  
  return results
    .sort((a, b) => b.score - a.score)
    .slice(0, 10)
    .map(r => r.entry);
}

function calculateSimilarity(a: string, b: string): number {
  if (a === b) return 1;
  if (a.length < 2 || b.length < 2) return 0;
  
  const bigrams = new Set<string>();
  for (let i = 0; i < a.length - 1; i++) {
    bigrams.add(a.slice(i, i + 2));
  }
  
  let matches = 0;
  for (let i = 0; i < b.length - 1; i++) {
    if (bigrams.has(b.slice(i, i + 2))) {
      matches++;
    }
  }
  
  return (2 * matches) / (a.length + b.length - 2);
}
