/**
 * Core Dictionary - Generated by scripts/merge_dictionaries.py
 * DO NOT EDIT MANUALLY - Run the script to regenerate
 * 
 * Tier 1: 231 high-frequency words (always loaded)
 * Tier 2: Extended vocabulary (lazy-loaded from JSON)
 * 
 * Source: Existing translations + seanghay/khmer-dictionary-44k
 */

export interface DictionaryEntry {
  khmer: string;
  english: string;
  pos?: 'noun' | 'verb' | 'adj' | 'adv' | 'pron' | 'prep' | 'conj' | 'part' | 'num';
  romanized?: string;
  phonetic?: string;
  frequency?: number;
}

export const coreDictionary: DictionaryEntry[] = [
  { khmer: 'សួស្តី', english: 'hello', pos: 'noun', romanized: 'suă-stei', phonetic: 'SUA-STAY', frequency: 100 },
  { khmer: 'អរគុណ', english: 'thank you', pos: 'noun', romanized: '\'rkŭ-nâ', phonetic: 'RKU-NA', frequency: 100 },
  { khmer: 'បាទ', english: 'yes (male)', pos: 'part', romanized: 'bā-tô', phonetic: 'BAH-TO', frequency: 100 },
  { khmer: 'ចាស', english: 'yes (female)', pos: 'part', romanized: 'chā-sâ', phonetic: 'CHAH-SA', frequency: 100 },
  { khmer: 'ទេ', english: 'no/not', pos: 'part', romanized: 'té', phonetic: 'TAY', frequency: 100 },
  { khmer: 'ខ្ញុំ', english: 'I/me', pos: 'pron', romanized: 'khñŏm', phonetic: 'KHNYOM', frequency: 100 },
  { khmer: 'អ្នក', english: 'you', pos: 'pron', romanized: '\'nâ-kâ', phonetic: 'NA-KA', frequency: 100 },
  { khmer: 'ទៅ', english: 'go', pos: 'verb', romanized: 'tŏu', phonetic: 'TOU', frequency: 100 },
  { khmer: 'មក', english: 'come', pos: 'verb', romanized: 'mkâ', phonetic: 'MKA', frequency: 100 },
  { khmer: 'មាន', english: 'have/there is', pos: 'verb', romanized: 'mā-nô', phonetic: 'MAH-NO', frequency: 100 },
  { khmer: 'មួយ', english: 'one', pos: 'num', romanized: 'muŏ-yô', phonetic: 'MUO-YO', frequency: 100 },
  { khmer: 'ពីរ', english: 'two', pos: 'num', romanized: 'pī-rô', phonetic: 'PEE-RO', frequency: 100 },
  { khmer: 'បី', english: 'three', pos: 'num', romanized: 'bei', phonetic: 'BAY', frequency: 100 },
  { khmer: 'សូម', english: 'please', pos: 'part', romanized: 'so-mô', phonetic: 'SOH-MO', frequency: 95 },
  { khmer: 'មិន', english: 'not', pos: 'adv', romanized: 'mĭ-nô', phonetic: 'MI-NO', frequency: 95 },
  { khmer: 'គាត់', english: 'he/she/they', pos: 'pron', romanized: 'kā-tâ', phonetic: 'KAH-TA', frequency: 95 },
  { khmer: 'នេះ', english: 'this', pos: 'pron', romanized: 'néh', phonetic: 'NAYH', frequency: 95 },
  { khmer: 'នោះ', english: 'that', pos: 'pron', romanized: 'noh', phonetic: 'NOHH', frequency: 95 },
  { khmer: 'ញ៉ាំ', english: 'eat', pos: 'verb', romanized: 'ñām', phonetic: 'NYAHM', frequency: 95 },
  { khmer: 'ដឹង', english: 'know', pos: 'verb', romanized: 'dœ̆-ngô', phonetic: 'DEU-NGO', frequency: 95 },
  { khmer: 'ចង់', english: 'want', pos: 'verb', romanized: 'chngô', phonetic: 'CHNGO', frequency: 95 },
  { khmer: 'ធ្វើ', english: 'do/make', pos: 'verb', romanized: 'thveu', phonetic: 'THVEU', frequency: 95 },
  { khmer: 'បួន', english: 'four', pos: 'num', romanized: 'buă-nô', phonetic: 'BUA-NO', frequency: 95 },
  { khmer: 'ប្រាំ', english: 'five', pos: 'num', romanized: 'brām', phonetic: 'BRAHM', frequency: 95 },
  { khmer: 'ដប់', english: 'ten', pos: 'num', romanized: 'dbâ', phonetic: 'DBA', frequency: 95 },
  { khmer: 'ថ្ងៃ', english: 'day', pos: 'noun', romanized: 'thngai', phonetic: 'THNGAI', frequency: 95 },
  { khmer: 'ផ្ទះ', english: 'house/home', pos: 'noun', romanized: 'phtâh', phonetic: 'PHTAH', frequency: 95 },
  { khmer: 'កម្ពុជា', english: 'Cambodia', pos: 'noun', romanized: 'kmpŭ-chā', phonetic: 'KMPU-CHAH', frequency: 95 },
  { khmer: 'បាយ', english: 'rice (cooked)', pos: 'noun', romanized: 'bā-yô', phonetic: 'BAH-YO', frequency: 95 },
  { khmer: 'ទឹក', english: 'water', pos: 'noun', romanized: 'tœ̆-kâ', phonetic: 'TEU-KA', frequency: 95 },
  { khmer: 'ម៉ែ', english: 'mother', pos: 'noun', romanized: 'mê', phonetic: 'MEH', frequency: 95 },
  { khmer: 'ប៉ា', english: 'father', pos: 'noun', romanized: 'bā', phonetic: 'BAH', frequency: 95 },
  { khmer: 'បង', english: 'older sibling', pos: 'noun', romanized: 'bngô', phonetic: 'BNGO', frequency: 95 },
  { khmer: 'អូន', english: 'younger sibling', pos: 'noun', romanized: '\'o-nô', phonetic: 'OH-NO', frequency: 95 },
  { khmer: 'ល្អ', english: 'good', pos: 'adj', romanized: 'l\'ô', phonetic: 'LO', frequency: 95 },
  { khmer: 'បាន', english: 'can/got/already', pos: 'verb', romanized: 'bā-nô', phonetic: 'BAH-NO', frequency: 95 },
  { khmer: 'នៅ', english: 'at/still', pos: 'prep', romanized: 'nŏu', phonetic: 'NOU', frequency: 95 },
  { khmer: 'និង', english: 'and', pos: 'conj', romanized: 'nĭ-ngô', phonetic: 'NI-NGO', frequency: 95 },
  { khmer: 'សូមទោស', english: 'sorry/excuse me', pos: 'noun', romanized: 'so-mto-sâ', phonetic: 'SOH-MTOH-SA', frequency: 90 },
  { khmer: 'យើង', english: 'we', pos: 'pron', romanized: 'yeu-ngô', phonetic: 'YEU-NGO', frequency: 90 },
  { khmer: 'អី', english: 'what', pos: 'pron', romanized: '\'ei', phonetic: 'AY', frequency: 90 },
  { khmer: 'អ្វី', english: 'what (formal)', pos: 'pron', romanized: '\'vei', phonetic: 'VAY', frequency: 90 },
  { khmer: 'ណា', english: 'where/which', pos: 'pron', romanized: 'nā', phonetic: 'NAH', frequency: 90 },
  { khmer: 'ផឹក', english: 'drink', pos: 'verb', romanized: 'phœ̆-kâ', phonetic: 'PHEU-KA', frequency: 90 },
  { khmer: 'និយាយ', english: 'speak/say', pos: 'verb', romanized: 'nĭ-yā-yô', phonetic: 'NI-YAH-YO', frequency: 90 },
  { khmer: 'មើល', english: 'look/watch', pos: 'verb', romanized: 'meu-lô', phonetic: 'MEU-LO', frequency: 90 },
  { khmer: 'ស្រឡាញ់', english: 'love', pos: 'verb', romanized: 'srâ-lā-ñô', phonetic: 'SRA-LAH-NYO', frequency: 90 },
  { khmer: 'ចូលចិត្ត', english: 'like', pos: 'verb', romanized: 'cho-lchĕ-ttâ', phonetic: 'CHOH-LCHE-TTA', frequency: 90 },
  { khmer: 'ប្រាំមួយ', english: 'six', pos: 'num', romanized: 'brām-muŏ-yô', phonetic: 'BRAHM-MUO-YO', frequency: 90 },
  { khmer: 'ប្រាំពីរ', english: 'seven', pos: 'num', romanized: 'brām-pī-rô', phonetic: 'BRAHM-PEE-RO', frequency: 90 },
  { khmer: 'ប្រាំបី', english: 'eight', pos: 'num', romanized: 'brām-bei', phonetic: 'BRAHM-BAY', frequency: 90 },
  { khmer: 'ប្រាំបួន', english: 'nine', pos: 'num', romanized: 'brām-buă-nô', phonetic: 'BRAHM-BUA-NO', frequency: 90 },
  { khmer: 'យប់', english: 'night', pos: 'noun', romanized: 'ybâ', phonetic: 'YBA', frequency: 90 },
  { khmer: 'ព្រឹក', english: 'morning', pos: 'noun', romanized: 'prœ̆-kâ', phonetic: 'PREU-KA', frequency: 90 },
  { khmer: 'ម៉ោង', english: 'hour/time', pos: 'noun', romanized: 'mau-ngô', phonetic: 'MAO-NGO', frequency: 90 },
  { khmer: 'ឥឡូវ', english: 'now', pos: 'adv', romanized: 'lo-vô', phonetic: 'LOH-VO', frequency: 90 },
  { khmer: 'ថ្ងៃនេះ', english: 'today', pos: 'noun', romanized: 'thngai-néh', phonetic: 'THNGAI-NAYH', frequency: 90 },
  { khmer: 'ផ្សារ', english: 'market', pos: 'noun', romanized: 'phsā-rô', phonetic: 'PHSAH-RO', frequency: 90 },
  { khmer: 'ក្នុង', english: 'in/inside', pos: 'prep', romanized: 'knŏ-ngô', phonetic: 'KNO-NGO', frequency: 90 },
  { khmer: 'មនុស្ស', english: 'person/people', pos: 'noun', romanized: 'mnŭ-ssâ', phonetic: 'MNU-SSA', frequency: 90 },
  { khmer: 'កូន', english: 'child', pos: 'noun', romanized: 'ko-nô', phonetic: 'KOH-NO', frequency: 90 },
  { khmer: 'ធំ', english: 'big', pos: 'adj', romanized: 'thôm', phonetic: 'THOM', frequency: 90 },
  { khmer: 'តូច', english: 'small', pos: 'adj', romanized: 'to-châ', phonetic: 'TOH-CHA', frequency: 90 },
  { khmer: 'ច្រើន', english: 'many/much', pos: 'adj', romanized: 'chraeu-nô', phonetic: 'CHREU-NO', frequency: 90 },
  { khmer: 'ប៉ុន្មាន', english: 'how many/much', pos: 'adv', romanized: 'bŏ-nmā-nô', phonetic: 'BO-NMAH-NO', frequency: 90 },
  { khmer: 'សុខសប្បាយ', english: 'fine/well', pos: 'adj', romanized: 'sŏ-khsbbā-yô', phonetic: 'SO-KHSBBAH-YO', frequency: 90 },
  { khmer: 'អត់ទេ', english: 'no/nothing', pos: 'part', romanized: '\'tâ-té', phonetic: 'TA-TAY', frequency: 90 },
  { khmer: 'មែន', english: 'right/true', pos: 'adj', romanized: 'mê-nô', phonetic: 'MEH-NO', frequency: 90 },
  { khmer: 'ឃើញ', english: 'see', pos: 'verb', romanized: 'kheu-ñô', phonetic: 'KHEU-NYO', frequency: 90 },
  { khmer: 'ទូរស័ព្ទ', english: 'phone', pos: 'noun', romanized: 'tū-rsptô', phonetic: 'TOO-RSPTO', frequency: 90 },
  { khmer: 'ឆ្នាំ', english: 'year', pos: 'noun', romanized: 'chhnām', phonetic: 'CHHNAHM', frequency: 90 },
  { khmer: 'គេ', english: 'they/people', pos: 'pron', romanized: 'ké', phonetic: 'KAY', frequency: 85 },
  { khmer: 'នរណា', english: 'who', pos: 'pron', romanized: 'nrnā', phonetic: 'NRNAH', frequency: 85 },
  { khmer: 'ស្តាប់', english: 'listen', pos: 'verb', romanized: 'stā-bâ', phonetic: 'STAH-BA', frequency: 85 },
  { khmer: 'អាន', english: 'read', pos: 'verb', romanized: '\'ā-nô', phonetic: 'AH-NO', frequency: 85 },
  { khmer: 'សរសេរ', english: 'write', pos: 'verb', romanized: 'srsé-rô', phonetic: 'SRSAY-RO', frequency: 85 },
  { khmer: 'គិត', english: 'think', pos: 'verb', romanized: 'kĭ-tâ', phonetic: 'KI-TA', frequency: 85 },
  { khmer: 'ដេក', english: 'sleep', pos: 'verb', romanized: 'dé-kâ', phonetic: 'DAY-KA', frequency: 85 },
  { khmer: 'ចាំ', english: 'wait/remember', pos: 'verb', romanized: 'chām', phonetic: 'CHAHM', frequency: 85 },
  { khmer: 'ទិញ', english: 'buy', pos: 'verb', romanized: 'tĭ-ñô', phonetic: 'TI-NYO', frequency: 85 },
  { khmer: 'យក', english: 'take', pos: 'verb', romanized: 'ykâ', phonetic: 'YKA', frequency: 85 },
  { khmer: 'រយ', english: 'hundred', pos: 'num', romanized: 'ryô', phonetic: 'RYO', frequency: 85 },
  { khmer: 'ល្ងាច', english: 'evening', pos: 'noun', romanized: 'lngā-châ', phonetic: 'LNGAH-CHA', frequency: 85 },
  { khmer: 'ថ្ងៃស្អែក', english: 'tomorrow', pos: 'noun', romanized: 'thngai-s\'ê-kâ', phonetic: 'THNGAI-SEH-KA', frequency: 85 },
  { khmer: 'សាលា', english: 'school', pos: 'noun', romanized: 'sā-lā', phonetic: 'SAH-LAH', frequency: 85 },
  { khmer: 'មុខ', english: 'front/face', pos: 'noun', romanized: 'mŭ-khâ', phonetic: 'MU-KHA', frequency: 85 },
  { khmer: 'ក្រោយ', english: 'behind/after', pos: 'prep', romanized: 'krau-yô', phonetic: 'KRAO-YO', frequency: 85 },
  { khmer: 'លើ', english: 'on/above', pos: 'prep', romanized: 'leu', phonetic: 'LEU', frequency: 85 },
  { khmer: 'សាច់', english: 'meat', pos: 'noun', romanized: 'sā-châ', phonetic: 'SAH-CHA', frequency: 85 },
  { khmer: 'ត្រី', english: 'fish', pos: 'noun', romanized: 'trei', phonetic: 'TRAY', frequency: 85 },
  { khmer: 'មិត្ត', english: 'friend', pos: 'noun', romanized: 'mĭ-ttâ', phonetic: 'MI-TTA', frequency: 85 },
  { khmer: 'អាក្រក់', english: 'bad', pos: 'adj', romanized: '\'ā-krâ-kâ', phonetic: 'AH-KRA-KA', frequency: 85 },
  { khmer: 'តិច', english: 'few/little', pos: 'adj', romanized: 'tĕ-châ', phonetic: 'TE-CHA', frequency: 85 },
  { khmer: 'ថ្មី', english: 'new', pos: 'adj', romanized: 'thmei', phonetic: 'THMAY', frequency: 85 },
  { khmer: 'ចាស់', english: 'old', pos: 'adj', romanized: 'chā-sâ', phonetic: 'CHAH-SA', frequency: 85 },
  { khmer: 'ឆ្ងាញ់', english: 'delicious', pos: 'adj', romanized: 'chhngā-ñô', phonetic: 'CHHNGAH-NYO', frequency: 85 },
  { khmer: 'ស្អាត', english: 'beautiful/clean', pos: 'adj', romanized: 's\'ā-tâ', phonetic: 'SAH-TA', frequency: 85 },
  { khmer: 'ថ្លៃ', english: 'expensive', pos: 'adj', romanized: 'thlai', phonetic: 'THLAI', frequency: 85 },
  { khmer: 'ហេតុអ្វី', english: 'why', pos: 'adv', romanized: 'hé-tŏ-\'vei', phonetic: 'HAY-TO-VAY', frequency: 85 },
  { khmer: 'យ៉ាងម៉េច', english: 'how', pos: 'adv', romanized: 'yā-ngmé-châ', phonetic: 'YAH-NGMAY-CHA', frequency: 85 },
  { khmer: 'ពេលណា', english: 'when', pos: 'adv', romanized: 'pé-lnā', phonetic: 'PAY-LNAH', frequency: 85 },
  { khmer: 'កំពុង', english: 'currently/-ing', pos: 'adv', romanized: 'kâm-pŭ-ngô', phonetic: 'KAM-PU-NGO', frequency: 85 },
  { khmer: 'រួច', english: 'already/finished', pos: 'adv', romanized: 'ruŏ-châ', phonetic: 'RUO-CHA', frequency: 85 },
  { khmer: 'ឬ', english: 'or', pos: 'conj', romanized: 'រឺ', frequency: 85 },
  { khmer: 'ប៉ុន្តែ', english: 'but', pos: 'conj', romanized: 'bŏ-ntê', phonetic: 'BO-NTEH', frequency: 85 },
  { khmer: 'ចេះ', english: 'know how to', pos: 'verb', romanized: 'chéh', phonetic: 'CHAYH', frequency: 85 },
  { khmer: 'ឮ', english: 'hear', pos: 'verb', romanized: 'លឺ', frequency: 85 },
  { khmer: 'បើក', english: 'open/drive', pos: 'verb', romanized: 'baeu-kâ', phonetic: 'BEU-KA', frequency: 85 },
  { khmer: 'ជួយ', english: 'help', pos: 'verb', romanized: 'chuŏ-yô', phonetic: 'CHUO-YO', frequency: 85 },
  { khmer: 'រៀន', english: 'learn/study', pos: 'verb', romanized: 'riĕ-nô', phonetic: 'RIA-NO', frequency: 85 },
  { khmer: 'ធ្វើការ', english: 'work', pos: 'verb', romanized: 'thveu-kā-rô', phonetic: 'THVEU-KAH-RO', frequency: 85 },
  { khmer: 'ស្រី', english: 'female', pos: 'noun', romanized: 'srei', phonetic: 'SRAY', frequency: 85 },
  { khmer: 'ប្រុស', english: 'male', pos: 'noun', romanized: 'brŏ-sâ', phonetic: 'BRO-SA', frequency: 85 },
  { khmer: 'ឡាន', english: 'car', pos: 'noun', romanized: 'lā-nô', phonetic: 'LAH-NO', frequency: 85 },
  { khmer: 'ម៉ូតូ', english: 'motorcycle', pos: 'noun', romanized: 'mo-to', phonetic: 'MOH-TOH', frequency: 85 },
  { khmer: 'ដៃ', english: 'hand/arm', pos: 'noun', romanized: 'dai', phonetic: 'DAI', frequency: 85 },
  { khmer: 'ជើង', english: 'foot/leg', pos: 'noun', romanized: 'cheu-ngô', phonetic: 'CHEU-NGO', frequency: 85 },
  { khmer: 'ខែ', english: 'month', pos: 'noun', romanized: 'khê', phonetic: 'KHEH', frequency: 85 },
  { khmer: 'សម្រាប់', english: 'for', pos: 'prep', romanized: 'smrā-bâ', phonetic: 'SMRAH-BA', frequency: 85 },
  { khmer: 'ជាមួយ', english: 'with/together', pos: 'prep', romanized: 'chā-muŏ-yô', phonetic: 'CHAH-MUO-YO', frequency: 85 },
  { khmer: 'គ្មាន', english: 'without/no', pos: 'adj', romanized: 'kmā-nô', phonetic: 'KMAH-NO', frequency: 85 },
  { khmer: 'បើ', english: 'if', pos: 'conj', romanized: 'baeu', phonetic: 'BEU', frequency: 85 },
  { khmer: 'ជឿ', english: 'believe', pos: 'verb', romanized: 'chœă', phonetic: 'CHEUA', frequency: 80 },
  { khmer: 'ក្រោក', english: 'wake up/get up', pos: 'verb', romanized: 'krau-kâ', phonetic: 'KRAO-KA', frequency: 80 },
  { khmer: 'ដើរ', english: 'walk', pos: 'verb', romanized: 'daeu-rô', phonetic: 'DEU-RO', frequency: 80 },
  { khmer: 'ឈប់', english: 'stop', pos: 'verb', romanized: 'chhbâ', phonetic: 'CHHBA', frequency: 80 },
  { khmer: 'លក់', english: 'sell', pos: 'verb', romanized: 'lkâ', phonetic: 'LKA', frequency: 80 },
  { khmer: 'ផ្តល់', english: 'give', pos: 'verb', romanized: 'phtâ-lô', phonetic: 'PHTA-LO', frequency: 80 },
  { khmer: 'ដាក់', english: 'put', pos: 'verb', romanized: 'dā-kâ', phonetic: 'DAH-KA', frequency: 80 },
  { khmer: 'ពាន់', english: 'thousand', pos: 'num', romanized: 'pā-nô', phonetic: 'PAH-NO', frequency: 80 },
  { khmer: 'នាទី', english: 'minute', pos: 'noun', romanized: 'nā-tī', phonetic: 'NAH-TEE', frequency: 80 },
  { khmer: 'ម្សិលមិញ', english: 'yesterday', pos: 'noun', romanized: 'msĭ-lmĭ-ñô', phonetic: 'MSI-LMI-NYO', frequency: 80 },
  { khmer: 'វត្ត', english: 'temple/pagoda', pos: 'noun', romanized: 'vttâ', phonetic: 'VTTA', frequency: 80 },
  { khmer: 'ភូមិ', english: 'village', pos: 'noun', romanized: 'phū-mĭ', phonetic: 'PHOO-MI', frequency: 80 },
  { khmer: 'ទីក្រុង', english: 'city', pos: 'noun', romanized: 'tī-krŏ-ngô', phonetic: 'TEE-KRO-NGO', frequency: 80 },
  { khmer: 'ប្រទេស', english: 'country', pos: 'noun', romanized: 'brâ-té-sâ', phonetic: 'BRA-TAY-SA', frequency: 80 },
  { khmer: 'ឆ្វេង', english: 'left', pos: 'noun', romanized: 'chhvé-ngô', phonetic: 'CHHVAY-NGO', frequency: 80 },
  { khmer: 'ស្តាំ', english: 'right', pos: 'noun', romanized: 'stām', phonetic: 'STAHM', frequency: 80 },
  { khmer: 'ក្រោម', english: 'under/below', pos: 'prep', romanized: 'krau-mô', phonetic: 'KRAO-MO', frequency: 80 },
  { khmer: 'ក្រៅ', english: 'outside', pos: 'prep', romanized: 'krau', phonetic: 'KRAO', frequency: 80 },
  { khmer: 'បន្លែ', english: 'vegetables', pos: 'noun', romanized: 'bnlê', phonetic: 'BNLEH', frequency: 80 },
  { khmer: 'ផ្លែឈើ', english: 'fruit', pos: 'noun', romanized: 'phlê-chheu', phonetic: 'PHLEH-CHHEU', frequency: 80 },
  { khmer: 'កាហ្វេ', english: 'coffee', pos: 'noun', romanized: 'kā-hvé', phonetic: 'KAH-HVAY', frequency: 80 },
  { khmer: 'តែ', english: 'tea', pos: 'noun', romanized: 'tê', phonetic: 'TEH', frequency: 80 },
  { khmer: 'ប្រពន្ធ', english: 'wife', pos: 'noun', romanized: 'brâ-pnthô', phonetic: 'BRA-PNTHO', frequency: 80 },
  { khmer: 'ប្តី', english: 'husband', pos: 'noun', romanized: 'btei', phonetic: 'BTAY', frequency: 80 },
  { khmer: 'ក្តៅ', english: 'hot', pos: 'adj', romanized: 'ktau', phonetic: 'KTAO', frequency: 80 },
  { khmer: 'ត្រជាក់', english: 'cold', pos: 'adj', romanized: 'trâ-chā-kâ', phonetic: 'TRA-CHAH-KA', frequency: 80 },
  { khmer: 'លឿន', english: 'fast', pos: 'adj', romanized: 'lœă-nô', phonetic: 'LEUA-NO', frequency: 80 },
  { khmer: 'ងាយ', english: 'easy', pos: 'adj', romanized: 'ngā-yô', phonetic: 'NGAH-YO', frequency: 80 },
  { khmer: 'ពិបាក', english: 'difficult', pos: 'adj', romanized: 'pĭ-bā-kâ', phonetic: 'PI-BAH-KA', frequency: 80 },
  { khmer: 'ថោក', english: 'cheap', pos: 'adj', romanized: 'thau-kâ', phonetic: 'THAO-KA', frequency: 80 },
  { khmer: 'ព្រោះ', english: 'because', pos: 'conj', romanized: 'proh', phonetic: 'PROHH', frequency: 80 },
  { khmer: 'ចាប់', english: 'catch/start', pos: 'verb', romanized: 'chā-bâ', phonetic: 'CHAH-BA', frequency: 80 },
  { khmer: 'បិទ', english: 'close', pos: 'verb', romanized: 'bĕ-tô', phonetic: 'BE-TO', frequency: 80 },
  { khmer: 'លេង', english: 'play', pos: 'verb', romanized: 'lé-ngô', phonetic: 'LAY-NGO', frequency: 80 },
  { khmer: 'ចូល', english: 'enter', pos: 'verb', romanized: 'cho-lô', phonetic: 'CHOH-LO', frequency: 80 },
  { khmer: 'ចេញ', english: 'exit/leave', pos: 'verb', romanized: 'ché-ñô', phonetic: 'CHAY-NYO', frequency: 80 },
  { khmer: 'ខ្ពស់', english: 'tall/high', pos: 'adj', romanized: 'khpâ-sâ', phonetic: 'KHPA-SA', frequency: 80 },
  { khmer: 'វែង', english: 'long', pos: 'adj', romanized: 'vê-ngô', phonetic: 'VEH-NGO', frequency: 80 },
  { khmer: 'រីករាយ', english: 'happy', pos: 'adj', romanized: 'rī-krā-yô', phonetic: 'REE-KRAH-YO', frequency: 80 },
  { khmer: 'អស់', english: 'finished/out of', pos: 'adj', romanized: '\'sâ', phonetic: 'SA', frequency: 80 },
  { khmer: 'កុំព្យូទ័រ', english: 'computer', pos: 'noun', romanized: 'kŏm-pyū-trô', phonetic: 'KOM-PYOO-TRO', frequency: 80 },
  { khmer: 'សៀវភៅ', english: 'book', pos: 'noun', romanized: 'siĕ-vphŏu', phonetic: 'SIA-VPHOU', frequency: 80 },
  { khmer: 'បន្ទប់', english: 'room', pos: 'noun', romanized: 'bntô-bâ', phonetic: 'BNTO-BA', frequency: 80 },
  { khmer: 'ភ្លៀង', english: 'rain', pos: 'noun', romanized: 'phliĕ-ngô', phonetic: 'PHLIA-NGO', frequency: 80 },
  { khmer: 'ដី', english: 'ground/land', pos: 'noun', romanized: 'dei', phonetic: 'DAY', frequency: 80 },
  { khmer: 'ក្បាល', english: 'head', pos: 'noun', romanized: 'kbā-lô', phonetic: 'KBAH-LO', frequency: 80 },
  { khmer: 'ភ្នែក', english: 'eye', pos: 'noun', romanized: 'phnê-kâ', phonetic: 'PHNEH-KA', frequency: 80 },
  { khmer: 'មាត់', english: 'mouth', pos: 'noun', romanized: 'mā-tâ', phonetic: 'MAH-TA', frequency: 80 },
  { khmer: 'សប្ដាហ៍', english: 'week', pos: 'noun', romanized: 'sbdā-hâ', phonetic: 'SBDAH-HA', frequency: 80 },
  { khmer: 'តាម', english: 'follow/according to', pos: 'prep', romanized: 'tā-mô', phonetic: 'TAH-MO', frequency: 80 },
  { khmer: 'ដោយ', english: 'by/with', pos: 'prep', romanized: 'dau-yô', phonetic: 'DAO-YO', frequency: 80 },
  { khmer: 'ដូច', english: 'like/as', pos: 'conj', romanized: 'do-châ', phonetic: 'DOH-CHA', frequency: 80 },
  { khmer: 'រត់', english: 'run', pos: 'verb', romanized: 'rtâ', phonetic: 'RTA', frequency: 75 },
  { khmer: 'ជិះ', english: 'ride', pos: 'verb', romanized: 'chĭh', phonetic: 'CHIH', frequency: 75 },
  { khmer: 'ភ្លេច', english: 'forget', pos: 'verb', romanized: 'phlé-châ', phonetic: 'PHLAY-CHA', frequency: 75 },
  { khmer: 'មន្ទីរពេទ្យ', english: 'hospital', pos: 'noun', romanized: 'mntī-rpé-tyô', phonetic: 'MNTEE-RPAY-TYO', frequency: 75 },
  { khmer: 'យឺត', english: 'slow', pos: 'adj', romanized: 'yœ-tâ', phonetic: 'YEU-TA', frequency: 75 },
  { khmer: 'ដូច្នេះ', english: 'so/therefore', pos: 'conj', romanized: 'do-chnéh', phonetic: 'DOH-CHNAYH', frequency: 75 },
  { khmer: 'បង្រៀន', english: 'teach', pos: 'verb', romanized: 'bngriĕ-nô', phonetic: 'BNGRIA-NO', frequency: 75 },
  { khmer: 'សម្រាក', english: 'rest', pos: 'verb', romanized: 'smrā-kâ', phonetic: 'SMRAH-KA', frequency: 75 },
  { khmer: 'កើត', english: 'be born/happen', pos: 'verb', romanized: 'kaeu-tâ', phonetic: 'KEU-TA', frequency: 75 },
  { khmer: 'កាត់', english: 'cut', pos: 'verb', romanized: 'kā-tâ', phonetic: 'KAH-TA', frequency: 75 },
  { khmer: 'ពេញ', english: 'full', pos: 'adj', romanized: 'pé-ñô', phonetic: 'PAY-NYO', frequency: 75 },
  { khmer: 'ទាប', english: 'short/low', pos: 'adj', romanized: 'tā-bâ', phonetic: 'TAH-BA', frequency: 75 },
  { khmer: 'ខ្លី', english: 'short (length)', pos: 'adj', romanized: 'khlei', phonetic: 'KHLAY', frequency: 75 },
  { khmer: 'ខ្លាច', english: 'afraid', pos: 'adj', romanized: 'khlā-châ', phonetic: 'KHLAH-CHA', frequency: 75 },
  { khmer: 'ខឹង', english: 'angry', pos: 'adj', romanized: 'khœ̆-ngô', phonetic: 'KHEU-NGO', frequency: 75 },
  { khmer: 'កង់', english: 'bicycle', pos: 'noun', romanized: 'kngô', phonetic: 'KNGO', frequency: 75 },
  { khmer: 'ទ្វារ', english: 'door', pos: 'noun', romanized: 'tvā-rô', phonetic: 'TVAH-RO', frequency: 75 },
  { khmer: 'សម្លៀកបំពាក់', english: 'clothes', pos: 'noun', romanized: 'smliĕ-kbâm-pā-kâ', phonetic: 'SMLIA-KBAM-PAH-KA', frequency: 75 },
  { khmer: 'ក្រដាស', english: 'paper', pos: 'noun', romanized: 'krâ-dā-sâ', phonetic: 'KRA-DAH-SA', frequency: 75 },
  { khmer: 'ព្រះអាទិត្យ', english: 'sun', pos: 'noun', romanized: 'prôh-\'ā-tĭ-tyâ', phonetic: 'PROH-AH-TI-TYA', frequency: 75 },
  { khmer: 'ខ្យល់', english: 'wind', pos: 'noun', romanized: 'khyâ-lô', phonetic: 'KHYA-LO', frequency: 75 },
  { khmer: 'ទន្លេ', english: 'river', pos: 'noun', romanized: 'tnlé', phonetic: 'TNLAY', frequency: 75 },
  { khmer: 'ដើមឈើ', english: 'tree', pos: 'noun', romanized: 'daeu-mchheu', phonetic: 'DEU-MCHHEU', frequency: 75 },
  { khmer: 'ត្រចៀក', english: 'ear', pos: 'noun', romanized: 'trâ-chiĕ-kâ', phonetic: 'TRA-CHIA-KA', frequency: 75 },
  { khmer: 'ច្រមុះ', english: 'nose', pos: 'noun', romanized: 'chrâ-mŭh', phonetic: 'CHRA-MUH', frequency: 75 },
  { khmer: 'ពោះ', english: 'stomach', pos: 'noun', romanized: 'poh', phonetic: 'POHH', frequency: 75 },
  { khmer: 'បេះដូង', english: 'heart', pos: 'noun', romanized: 'béh-do-ngô', phonetic: 'BAYH-DOH-NGO', frequency: 75 },
  { khmer: 'ជានិច្ច', english: 'always', pos: 'adv', romanized: 'chā-nĭ-chchâ', phonetic: 'CHAH-NI-CHCHA', frequency: 75 },
  { khmer: 'ពេលខ្លះ', english: 'sometimes', pos: 'adv', romanized: 'pé-lkhlâh', phonetic: 'PAY-LKHLAH', frequency: 75 },
  { khmer: 'មិនដែល', english: 'never', pos: 'adv', romanized: 'mĭ-ndê-lô', phonetic: 'MI-NDEH-LO', frequency: 75 },
  { khmer: 'អំពី', english: 'about/around', pos: 'prep', romanized: '\'âm-pī', phonetic: 'AM-PEE', frequency: 75 },
  { khmer: 'ក្រហម', english: 'red', pos: 'adj', romanized: 'krâ-hmô', phonetic: 'KRA-HMO', frequency: 75 },
  { khmer: 'ស', english: 'white', pos: 'adj', romanized: 'sâ', phonetic: 'SA', frequency: 75 },
  { khmer: 'ខ្មៅ', english: 'black', pos: 'adj', romanized: 'khmau', phonetic: 'KHMAO', frequency: 75 },
  { khmer: 'ស្រា', english: 'alcohol/wine', pos: 'noun', romanized: 'srā', phonetic: 'SRAH', frequency: 70 },
  { khmer: 'ស្លាប់', english: 'die', pos: 'verb', romanized: 'slā-bâ', phonetic: 'SLAH-BA', frequency: 70 },
  { khmer: 'ដឹក', english: 'transport/carry', pos: 'verb', romanized: 'dœ̆-kâ', phonetic: 'DEU-KA', frequency: 70 },
  { khmer: 'ទទេ', english: 'empty', pos: 'adj', romanized: 'tté', phonetic: 'TTAY', frequency: 70 },
  { khmer: 'ក្រៀមក្រំ', english: 'sad', pos: 'adj', romanized: 'kriĕ-mkrâm', phonetic: 'KRIA-MKRAM', frequency: 70 },
  { khmer: 'មេរៀន', english: 'lesson', pos: 'noun', romanized: 'mé-riĕ-nô', phonetic: 'MAY-RIA-NO', frequency: 70 },
  { khmer: 'បង្អួច', english: 'window', pos: 'noun', romanized: 'bng\'uŏ-châ', phonetic: 'BNGUO-CHA', frequency: 70 },
  { khmer: 'ស្បែកជើង', english: 'shoes', pos: 'noun', romanized: 'sbê-kcheu-ngô', phonetic: 'SBEH-KCHEU-NGO', frequency: 70 },
  { khmer: 'ប៊ិច', english: 'pen', pos: 'noun', romanized: 'bĭ-châ', phonetic: 'BI-CHA', frequency: 70 },
  { khmer: 'អាកាសធាតុ', english: 'weather', pos: 'noun', romanized: '\'ā-kā-sthā-tŏ', phonetic: 'AH-KAH-STHAH-TO', frequency: 70 },
  { khmer: 'ព្រះច័ន្ទ', english: 'moon', pos: 'noun', romanized: 'prôh-chntô', phonetic: 'PROH-CHNTO', frequency: 70 },
  { khmer: 'មេឃ', english: 'sky', pos: 'noun', romanized: 'mé-khô', phonetic: 'MAY-KHO', frequency: 70 },
  { khmer: 'ភ្នំ', english: 'mountain', pos: 'noun', romanized: 'phnôm', phonetic: 'PHNOM', frequency: 70 },
  { khmer: 'សមុទ្រ', english: 'sea/ocean', pos: 'noun', romanized: 'smŭ-trô', phonetic: 'SMU-TRO', frequency: 70 },
  { khmer: 'ផ្កា', english: 'flower', pos: 'noun', romanized: 'phkā', phonetic: 'PHKAH', frequency: 70 },
  { khmer: 'ធ្មេញ', english: 'tooth', pos: 'noun', romanized: 'thmé-ñô', phonetic: 'THMAY-NYO', frequency: 70 },
  { khmer: 'ខ្នង', english: 'back', pos: 'noun', romanized: 'khnâ-ngô', phonetic: 'KHNA-NGO', frequency: 70 },
  { khmer: 'រហូត', english: 'until', pos: 'prep', romanized: 'rho-tâ', phonetic: 'RHOH-TA', frequency: 70 },
  { khmer: 'ដោយសារ', english: 'because of', pos: 'conj', romanized: 'dau-ysā-rô', phonetic: 'DAO-YSAH-RO', frequency: 70 },
  { khmer: 'ពណ៌', english: 'color', pos: 'noun', romanized: 'pnâ', phonetic: 'PNA', frequency: 70 },
  { khmer: 'លឿង', english: 'yellow', pos: 'adj', romanized: 'lœă-ngô', phonetic: 'LEUA-NGO', frequency: 70 },
  { khmer: 'បៃតង', english: 'green', pos: 'adj', romanized: 'bai-tngô', phonetic: 'BAI-TNGO', frequency: 70 },
  { khmer: 'ខៀវ', english: 'blue', pos: 'adj', romanized: 'khiĕ-vô', phonetic: 'KHIA-VO', frequency: 70 },
];

// Build lookup maps for efficient access
const khmerToEntryMap = new Map<string, DictionaryEntry>();
const phoneticToEntryMap = new Map<string, DictionaryEntry[]>();

for (const entry of coreDictionary) {
  khmerToEntryMap.set(entry.khmer, entry);
  
  if (entry.phonetic) {
    const normalized = entry.phonetic.toLowerCase().replace(/-/g, '');
    if (!phoneticToEntryMap.has(normalized)) {
      phoneticToEntryMap.set(normalized, []);
    }
    phoneticToEntryMap.get(normalized)!.push(entry);
  }
}

/**
 * Look up a Khmer word in the dictionary
 */
export function lookupKhmer(word: string): DictionaryEntry | null {
  return khmerToEntryMap.get(word) || null;
}

/**
 * Fuzzy search by phonetic approximation
 */
export function searchByPhonetic(query: string): DictionaryEntry[] {
  const normalized = query.toLowerCase().replace(/[-\s]/g, '');
  const results: Array<{ entry: DictionaryEntry; score: number }> = [];
  
  for (const entry of coreDictionary) {
    if (!entry.phonetic) continue;
    
    const entryPhonetic = entry.phonetic.toLowerCase().replace(/-/g, '');
    const score = calculateSimilarity(normalized, entryPhonetic);
    
    if (score > 0.4) {
      results.push({ entry, score });
    }
  }
  
  return results
    .sort((a, b) => b.score - a.score)
    .slice(0, 10)
    .map(r => r.entry);
}

/**
 * Search by English meaning
 */
export function searchByEnglish(query: string): DictionaryEntry[] {
  const normalized = query.toLowerCase();
  const results: Array<{ entry: DictionaryEntry; score: number }> = [];
  
  for (const entry of coreDictionary) {
    if (!entry.english) continue;
    const english = entry.english.toLowerCase();
    
    if (english === normalized) {
      results.push({ entry, score: 1 });
      continue;
    }
    
    if (english.includes(normalized) || normalized.includes(english)) {
      const score = Math.min(normalized.length, english.length) / Math.max(normalized.length, english.length);
      results.push({ entry, score: score * 0.8 });
    }
  }
  
  return results
    .sort((a, b) => b.score - a.score)
    .slice(0, 10)
    .map(r => r.entry);
}

function calculateSimilarity(a: string, b: string): number {
  if (a === b) return 1;
  if (a.length < 2 || b.length < 2) return 0;
  
  const bigrams = new Set<string>();
  for (let i = 0; i < a.length - 1; i++) {
    bigrams.add(a.slice(i, i + 2));
  }
  
  let matches = 0;
  for (let i = 0; i < b.length - 1; i++) {
    if (bigrams.has(b.slice(i, i + 2))) {
      matches++;
    }
  }
  
  return (2 * matches) / (a.length + b.length - 2);
}
